### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by Xavvierr** [cengelha/NomNom#1]
I double clicked the .exe and crashed right away.

**Type**
System.Windows.Markup.XamlParseException

**Message**
The invocation of the constructor on type 'NomNom.ViewModel.MainViewModel' that matches the specified binding constraints threw an exception.

**Source**
PresentationFramework

**Stack Trace**
n System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   en System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   en System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   en System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   en System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   en System.Windows.Application.DoStartup()
   en System.Windows.Application.<.ctor>b__1_0(Object unused)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by cengelha** [comment]
Thanks for the report! I could reproduce it when the Steam/GOG.com default save location does not exists.

Do you by chance use the Microsoft Store version or can you confirm that `C:\User\<your username>\AppData\Roaming\HelloGames\NMS` does not exist on your system?

**Comment by Xavvierr** [comment]
Yes I am using the windows store version, I wanted to see if I could modify anything. However, that directory does exists in my system, that's where the save files are placed.

**Comment by cengelha** [comment]
Interesting. This is the save location for Steam/GOG.com (MS Store puts it in AppData\Local\Packages\HelloGames.NoMansSky_bs190hzg1sesy\SystemAppData\wgs) but it seems that they use it for the cache anway. Or did you use the Steam/GOG.com version before?

FYI the MS Store version is not yet compatible but there are already running some efforts in the background but this may take a while.

Nonetheless this is not an intended behavior and I will fix what I'll find (there are definitely some unhandled errors in the directory stuff).
Would be nice if you confirm whether this is resolved or not in the next release, regardless of the MS Store compatibility.

**Comment by Xavvierr** [comment]
No, I have never used No Man's Sky before, I do not own the Steam nor the GOG version, only MS store version. 

I knew it wasn't compatible yet but I was hoping maybe not fully compatible but partly, I still wanted to try if I could at least modify the nanite clusters and that's it.

Yeah, whenever you release the next one, I'll let you know.
