### ISSUE TITLE
Crash on launch with new update, saves still not "Compatible"

### ISSUE THREAD

**Issue by OmegaX123** [cengelha/NomNom#17]
I updated because the issue I was having before (incompatible saves with "'Not Found' was not found" bug) was reported as fixed, and now the program crashes on launch. Deleted and redownloaded fresh, and saves are still not showing as "Compatible" and can't be edited. Log attached.
[NomNom20201004.log](https://github.com/cengelha/NomNom/files/5324450/NomNom20201004.log)

**Comment by cengelha** [comment]
Well... That fix made a new bug... Damit. Thanks for reporting again.

**Comment by cengelha** [comment]
Would you attach your wgs folder here so I can verify that the next fix works?

**Comment by OmegaX123** [comment]
I assume you mean my folder for the game from the Windows Store install? I'm using the workaround that allows modding via dumping the game files and unlocking and moving them, not sure what I would need to attach then, and I doubt I can attach my whole game folder as it's over 10 gb.

**Comment by cengelha** [comment]
The folder with your saves: AppData\Local\Packages\HelloGames.NoMansSky_bs190hzg1sesy\SystemAppData\wgs

**Comment by OmegaX123** [comment]
Ah, that makes sense. I'll do that now.
[wgs.zip](https://github.com/cengelha/NomNom/files/5324486/wgs.zip)

**Comment by cengelha** [comment]
New update. Worked fine for me. I let this issue open until you confirm that it's fixed for you as well.

**Comment by OmegaX123** [comment]
Seems good so far, Compatible is checked. Editor non-greyed. Just have to find out if the edits stick, which would be a different issue altogether if they don't.

**Comment by OmegaX123** [comment]
There is an issue with the Knowledge tab, it's lacking scrollbars so I can't see all the unlocks, but again, different issue.

**Comment by cengelha** [comment]
Finally fixed!
Yeah... That tab is mess, I know but please don't open an issue for that.
The next planned release will be primarily about sanitizing all that stuff. Code and UI clean up. Maybe even switch from alpha to beta.
