### ISSUE TITLE
Crash Error: Loading the PS4 Memory.dat folder.

### ISSUE THREAD

**Issue by Aeramis** [cengelha/NomNom#18]
Here you go. Honestly, I think I must be doing something wrong and it isn't the program. Right now when I load the program it is auto linked to the Steam save I have. So maybe that is the issue. 

[report.zip](https://github.com/cengelha/NomNom/files/5324634/report.zip)

**Comment by cengelha** [comment]
No that hasn't anything to do with the Steam path. 

Do you use SaveWizard or SaveMounter?
Could it be that you modified your memory.dat manually before? The report says that there is more data than expected so I assume it read more bytes than the json part actually has which could happen if the metadata at the beginning of the file doesn't match the actual data.

Would you attach your memory.dat here? Then I can anaylse it to be sure what happens.

**Comment by Aeramis** [comment]
Ahh.. That might be the issue, I was using a modified dat file. Let me get my save loaded in the game and then save via game again. I'll let you know.

**Comment by Aeramis** [comment]
Ok, I am able to get it to load in the program. I can't seem to save it though as it crashes. Does the memory.dat need to be in a specific folder? 

I added a few things to the save, also, I noticed that some of item products have a higher amount for Max Amount. For example, Atlas Stones show Max Amount of 10 when it should only be 5 per stack. 
[report.zip](https://github.com/cengelha/NomNom/files/5328921/report.zip)
Here is the report.

**Comment by cengelha** [comment]
No, no specific folder necessary. It's now the same bug as in #20 and will be fixed in the next release.

About the stacks: Don't know but maybe HG changed it in Origins for the stones (they definitely did for some items). The next planned release (see [roadmap](ROADMAP.md) will cleanup a lot of the current mess and if it's not the right stack size now, it will be then.

**Comment by Aeramis** [comment]
Just checking up to see how progress is going?
