### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by Temporel** [cengelha/NomNom#2]
I have both the GOG and STEAM version of the game installed on my PC. I am using the NMSSaveEditor for years and want to give a try to your program. Hope we'll find a way to make it works.

**Type**
System.Reflection.TargetInvocationException

**Message**
Une exception a été levée par la cible d'un appel. (French version of the crash report)
The target of a call trew an exception. (my translation)

**Source**
mscorlib

**Stack Trace**
   à System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   à System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance(Type type, Boolean nonPublic)
   à System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   à System.Activator.CreateInstance(Type type, Object[] args)
   à System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
   à System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   à MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
   à MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.CreateInstance(XamlType xamlType, Object[] args)
   à System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
   à System.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
   à System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   à System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   à System.Windows.Application.DoStartup()
   à System.Windows.Application.<.ctor>b__1_0(Object unused)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by cengelha** [comment]
Thanks for the report! If this bug persists in the next version, could you update this issue with details of the InnerException from the report.html? I just added that part to the CrashReporter as these details are not helping, unfortunatly...

**Comment by SubsterNL** [comment]
Just wanted to say that I recentely started playing again after no play for years and decided to 'the other editor' but for the life of me I couldn't get it to work.

Your editor worked from the start and even though it isn't supposed to support the latest game version, it appears to do exactly what it is supposed to, actually work!! Thanks a lot... Sorry for posting this here but didn't know where else.

**Comment by cengelha** [comment]
@SubsterNL Thanks. Glad you like it. About your error: Please wait for the next release before posting it. I fixed all the open issues and much more. So hopefully your problem resolves itself with the next one. Shouldn't be far away anymore (one last thing that needs to be implemented).
