### ISSUE TITLE
Crash attempting to save Windows Store version edited save file

### ISSUE THREAD

**Issue by OmegaX123** [cengelha/NomNom#20]
Crashed with the error "Cannot write a null value for property 'iAF'. Property requires a value. Path '6f=.30s'."

[report.zip](https://github.com/cengelha/NomNom/files/5324883/report.zip)

**Comment by SkullOG** [comment]
+ Support i seem to be having the same issue.

**Comment by cengelha** [comment]
-.- It was already very late when I released a10 yesterday and just after I released it I already had a feeling the I may missed something...
I will have another look at it after work
