### ISSUE TITLE
having a problem opening

### ISSUE THREAD

**Issue by rexrobotwars** [cengelha/NomNom#32]
when i download and open the file it was a bit hard to find the executable but once i found it i immediately tried runing it. it only showed a starting up page and never really opened i tried running in other ways after i checked my antivirus and it came up empty i figured something else must be wrong, plz help?

**Comment by cengelha** [comment]
Did it start with an empty manager or not at all?

If it's empty it couldn't find a save in the default locations. Which platform do you use?

If it doesn't start at all, can you have a look at the log file (there should be a *log* folder in the same folder as the executable) if there is something?

But in general you don't need something special to do. Just download the zip, extract it, and execute NomNom.exe.

**Comment by mookrhodan** [comment]
I had same problem, I am on Win10 Enterprise, Steam installed on separate HDD (non-standard location). Initially put NomNom under NMS folder, only had the start-up image pop-up, then nothing.... Moved nomnom folder to root of HDD and it starts, looks like the app cant locate game / saves location from non-standard locations (Path environmental variable...), Hope this helps to fix the issue.... nice app, looking forward to next update!

**Comment by cengelha** [comment]
I will see if I can reproduce it. If one of you could check the log file of the timeframe when it happened that would be great

**Comment by rexrobotwars** [comment]
it probs was my antivirus being tricky because after a bit of tinkering
things worked out swell, oh and thanks for your beautiful creation i know
that in due time it will become a wonderful save editor, glad to see a
editor for the microsoft version tho lol

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mookrhodan** [comment]
App Location: F:\#steamapps\common\No Man's Sky\NomNom

Started nomnom.exe, initial start-up logo, then nothing, also no log file generated in above location. Then searched c:\ and found two references but cant attach screenshot nor logfile here, so email me if you want it send over...

It would be nice if the folder in AppData/Local would not have such a weird name, I probably would delete that immediately when I find something of such naming convention….

Let me know if you need more info

**Comment by cengelha** [comment]
Thanks for the notes.

@mookrhodan That folder name is auto-generated by .NET itself and therefore I have no control over it.

**Comment by cengelha** [comment]
@mookrhodan The next update is just around the corner, and I also changed the settings to be stored portable next to the executable now. No weird names anymore ;)
