### ISSUE TITLE
[Feature Request] Randomize Procedural tech button

### ISSUE THREAD

**Issue by micmou** [cengelha/NomNom#39]
## Summary

A button to randomize all the procedural tech in a ship or multitool

## Details

This would be a button or right click feature to randomize the procedural tech seed or id. This would allow hunting for perfect modules specifically X-Class ones much more feasible allowing a indivisual to check lots and lots of seeds at a time. 

Another thing that could be done is when the perfect seed for a piece of tech is found and verified I or others can post its seed here and you could add it to the catalogue of know perfect seeds.

**Comment by cengelha** [comment]
Thanks for the suggention! I already planned that for ships and weapons and proc tech shall not be forgotten! Added it already to my local roadmap.

**Comment by cengelha** [comment]
@micmou I'll close this as there is no need for hunting anymore.

You can find all the stats to a seed here: https://github.com/zencq/Pi
This will also be integrated into the editor itself with a future release.
