### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by KeishaGrill** [cengelha/NomNom#50]
### Crash on start

I dont know why i cannot open the editor, it just crashes on start (on every single version, but the screenshots are from alpha 14)

### Steps to Reproduce

1. Open the .exe file

### Screenshots
![image](https://user-images.githubusercontent.com/86205136/122685894-e712b680-d1d3-11eb-944c-cddabffe5205.png)

![image](https://user-images.githubusercontent.com/86205136/122685886-de21e500-d1d3-11eb-9d3c-d36a903b5112.png)

![image](https://user-images.githubusercontent.com/86205136/122685882-dbbf8b00-d1d3-11eb-9f82-c2cad2a42529.png)

**Comment by cengelha** [comment]
@KeishaGrill Can you please post the crash report? It's in the "crash" folder next to the executable.
Thanks!

**Comment by KeishaGrill** [comment]
> @KeishaGrill Can you please post the crash report? It's in the "crash" folder next to the executable.
> Thanks!

Here is the thing: i dont have that folder anymore cause i just deleted that and tried another version again (it didnt work as well). But i attempted it today as well as you requested the crash report, and for my surprise the program doesnt crash on start (no changes in my system were made as far as im aware of, if that could be a potential reason to think about). So i cannot provide that anymore, now the catch here is that it states that my save is not compatible with the current version of the editor (alpha 15). Thank you anyways for your response and sorry for troubling. Hope you get the updated version soon. If i have any problems of some sort with the thing again I will let you know with the proper crash report to see if that gives any feedback or helps

**Comment by cengelha** [comment]
@KeishaGrill  Ok, no problem. Thanks for the update.
The next release is scheduled for tomorrow btw, so the wait is over very soon! That it shows it as not compatible is currently normal as a recent game update broke it. The update will fix this and more.
