### ISSUE TITLE
[Feature Request] Linux support?

### ISSUE THREAD

**Issue by Jimi-James** [cengelha/NomNom#51]
## Summary

Linux/WINE/SteamPlay/Proton etc.

## Details

I just tried to get this to run in wine/proton, but for the life of me I cannot get .NET 4.0 installed into the No Man's Sky prefix no matter what I try, so it's a no-go. I'm assuming that's the issue because trying to launch this gets me an error implying it needs .NET 4.0.

If this program was fully compatible with a mono-only system, then things would probably be simpler, even if you don't want to support any further from there.

**Comment by cengelha** [comment]
@Jimi-James Yes, it requires .NET Framework 4.8 which is Windows-only, so I don't think this will ever work outside Windows itself. But I'm planning to upgrade to .NET 5 which is cross-platform.
Once this is done and it still won't work for you, we can work it out together

**Comment by cengelha** [comment]
This won't be possible in the foreseeable future I'm afraid. 
The .NET Desktop Runtime is still limited to Windows and even their new MAUI framework doesn't support Linux.
I'll close this for now. Maybe someday, there will be some news that will change that.

**Comment by maiainternet** [comment]
Hi, now that you're running on dotnet 6, which is cross platform, how would we go about running this on Linux?

thanks
