### ISSUE TITLE
[Feature Request] Freighter Rescue Mission Readiness

### ISSUE THREAD

**Issue by weasel-nms** [cengelha/NomNom#55]
## Summary

NomNom has already implemented a great UI on top of existing NMS save file information read/write conversion, and it seems a great tool in which to add some reporting.

Specifically for this feature request, NomNom could provide a display of a save's readiness for whether a freighter rescue mission will be triggered with the next hyperspace jump.  This information is a constant source of confusion for many players as evidenced by questions posed in the help channel of the No Man's Sky Discord server.

## Details

This readiness calculation is easy to perform.  Four values must be retrieved from the save file:

1. The time index of the last freighter rescue mission is stored in "PlayerStateData.TimeLastSpaceBattle"
2. The running count of the number of hyperspace jumps since the last freighter rescue mission is stored in "PlayerStateData.WarpsLastSpaceBattle"
3. The total time played in this save is stored in "PlayerStateData.TotalPlaytime"
4. The total number of warps performed in this save can be found in "PlayerStateData.Stats.Stats", where "id" equals "^DIST_WARP"

Once we retrieve those four values from the save file, there are two numerical comparisons to be made, and several user notices:

1. If the difference between the timestamp of the last freighter battle and now is less than 3 hours (10800 seconds), then it's not ready.  If < 10800 seconds has lapsed, then a suggestion would be to indicate that x minutes of additional gameplay time must lapse before the next freighter rescue can be triggered.
2. If the number of warps since the last freighter battle is less than 4, then the next jump cannot result in a freighter battle.  A suggestion would be to indicate that x more jumps are needed to trigger a freighter rescue if it's < 4.
3. If both the time difference is >= 90 minutes *and* the total number of warps since the last battle >= 4, then a suggestion would be to indicate that the next hyperspace jump will trigger a freighter battle.

**Comment by cengelha** [comment]
Hi, thanks for suggestions! This one is actually already implemented. Not great (UI wise) but it'll show you the time and warps until the next battle and you can also trigger it.
![2021-08-18 (2)_LI](https://user-images.githubusercontent.com/37042388/129809644-8844a5cd-5117-422d-b8df-7c0acf75836c.jpg)
