### ISSUE TITLE
[Feature Request] Base part count information display

### ISSUE THREAD

**Issue by weasel-nms** [cengelha/NomNom#56]
## Summary

NomNom has already implemented a great UI on top of existing NMS save file information read/write conversion, and it seems a great tool in which to add some reporting.  Creative base building in NMS is a favorite activity for many people, but the game has a soft limit of 3000 parts per base before it can no longer be uploaded (i.e., shared), and a hard limit of 16000 total base parts across all bases before the game prevents further part construction.  Players cannot find these stats in-game; they can be retrieved from the save file and displayed in NomNom.

## Details

A "base", as it pertains to counting against your build part total, is any entry of type "HomePlanetBase" or "FreighterBase" as stored under "PlayerStateData.PersistentPlayerBases".  (It is not clear to the feature requestor at this time if entries of type "ExternalPlanetBase", or potentially other types, can exist in this section.)

For each "HomePlanetBase" or "FreighterBase" entry - which should correlate to each base displayed on the Base tab on NomNom (although the freighter base may not be currently included in this list) - a suggestion would be to display the current number of base parts.  It might also be beneficial to display how many additional parts are possible before breaching the 3000 part upload limit for the base.

Then, somewhere else in the Base tab, NomNom can tally all of the base parts in all of the bases, subtract it from 16000, and display a total additional base parts possible.

**Comment by cengelha** [comment]
This partially already available. You can see how many parts a base uses. I
'll put the rest on the todo list. Do you know whether the "BaseBuildungObjects" (objects outside a base like beacons) are also counted towards the global limit?

**Comment by cengelha** [comment]
@weasel-nms Would you do another run to see whether they increased the base building limit with Frontiers?
