### ISSUE TITLE
[Bug] Cannot change unlocked blueprints

### ISSUE THREAD

**Issue by nxtdaydelivery** [cengelha/NomNom#58]
### Description
  I want to unlock the standing planter, but the checkbox does not respond. I cannot change any of my unlocked technologies.

### Steps to Reproduce

1. Try to unlock (using checkbox) a blueprint.
2. Notice it does not work.
3.

### Expected Behavior
   Ability to modify unlocked blueprints using the checkbox.
### Actual Behavior
   Cannot edit.
### Basic Information

- Version with issue: 3.1.0.16-alpha.16
- Platform you use: Windows Store (win10)

**Comment by cengelha** [comment]
Yes. Due to the necessary Frontiers compat update the version for this moved one up. I also renamed the milestones to a more descriptive name to avoid confusion like this in the future.
