### ISSUE TITLE
[Feature Request] Support for Frontiers Update

### ISSUE THREAD

**Issue by louanfontenele** [cengelha/NomNom#62]
Please add support to the new version! Thanks

**Comment by TempAccountNull** [comment]
> 
> 
> Please add support to the new version! Thanks

He's literally looking into it. You gotta remember, they changed the encryption this time around it seems, so all that work has to be re-decrypted and re-arranged to load your save data. The JSON function has to be completely re-written. This is gonna take some time. So, please, be patient. It'll be out as soon as he figures out what changed as he's still obtaining saves and other data like crash reports to understand what exactly changed.
