### ISSUE TITLE
[Bug] Crashes on startup

### ISSUE THREAD

**Issue by Yufukuai** [cengelha/NomNom#63]
### Steps to Reproduce

1. Open the program
2. Wait a few seconds
3. It crashes

### Expected Behavior

To work after having the .NET runtimes installed and opening the exe normally.

### Actual Behavior

It shows the loading image of the frontiers update and then crashes, showing a window explaining the error

### Basic Information

- Version with issue: 3.6.0.18-alpha.18
- Platform you use: Steam

### HTML Report

**Exception**

**Type**
System.Windows.Markup.XamlParseException

**Message**
La invocación del constructor del tipo 'NomNom.ViewModel.MainViewModel' que coincide con las restricciones de enlace especificadas produjo una excepción.

**Source**
PresentationFramework

**Stack Trace**
en System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
en System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
en System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
en System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
en System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
en System.Windows.Application.DoStartup()
en System.Windows.Application.<.ctor>b__1_0(Object unused)
en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**InnerException**

**Type**
System.AggregateException

**Message**
Se han producido uno o varios errores.

**Source**
mscorlib

**Stack Trace**
en System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
en NomNom.IO.IPlatform.BuildContainerCollection()
en NomNom.IO.PlatformFactory.GetPlatform(PlatformEnum platformEnum, String path, String& relocated)
en NomNom.IO.PlatformFactory.GetPlatform(String path, String& relocated)
en NomNom.Manager.SetSavePath(String path)
en NomNom.Manager.Initialize()
en NomNom.ViewModel.MainViewModel..ctor()

**InnerException**

**Type**
System.ArgumentOutOfRangeException

**Message**
El índice estaba fuera del intervalo. Debe ser un valor no negativo e inferior al tamaño de la colección. Nombre del parámetro: index

**Source**
mscorlib

**Stack Trace**
en System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
en NomNom.IO.PlatformSteam.DecryptMeta(Container container, Byte[] meta)
en NomNom.IO.IPlatform.LoadMeta(Container container)
en NomNom.IO.PlatformSteam.LoadContainer(Container container)
en NomNom.IO.IPlatform.BuildContainer(Int32 index, Container container, Object data)
en NomNom.IO.IPlatform.<>c__DisplayClass89_1.<BuildContainerCollection>b__1()
en System.Threading.Tasks.Task.Execute()

**Comment by dvkkha** [comment]
I second this. Exactly same behavior on my end. Windows 10, latest build and .NET Framework.

**Comment by unitedemperor** [comment]
at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NomNom.IO.IPlatform.BuildContainerCollection()
   at NomNom.IO.PlatformFactory.GetPlatform(PlatformEnum platformEnum, String path, String& relocated)
   at NomNom.IO.PlatformFactory.GetPlatform(String path, String& relocated)
   at NomNom.Manager.SetSavePath(String path)
   at NomNom.Manager.Initialize()
   at NomNom.ViewModel.MainViewModel..ctor()

**Comment by Alidar78** [comment]
> 
> 
> I second this. Exactly same behavior on my end. Windows 10, latest build and .NET Framework.

Crashes Immediately, Also have latest of both win10 and .net

**Comment by cengelha** [comment]
Can you send me your save folder? I don't have any of those crashes and need something to reproduce it. Thanks!

**Comment by unitedemperor** [comment]
> Can you send me your save folder? I don't have any of those crashes and need something to reproduce it. Thanks!

![save](https://user-images.githubusercontent.com/6275028/132132319-acb6b525-b95f-46a0-a254-98138c5aeb62.PNG)

**Comment by Yufukuai** [comment]
> Can you send me your save folder? I don't have any of those crashes and need something to reproduce it. Thanks!

Should I upload the save folder to Google Drive or something? If yes, where to? Or should I just send a screenshot of the folder?

**Comment by Alidar78** [comment]
> 
> 
> Can you send me your save folder? I don't have any of those crashes and need something to reproduce it. Thanks!

I'm not sure how to do that, i'm really Noob-ish with this kind of stuff

**Comment by Alidar78** [comment]
[st_76561198027823396.zip](https://github.com/cengelha/NomNom/files/7111975/st_76561198027823396.zip)

**Comment by cengelha** [comment]
@Yufukuai As you like. Upload to cloud storage and post link here, or directly attach it here as Alidar78 did.
We figured out Alidar78s cause on my Discord but yours might be different. I would like to have a look at yours too

**Comment by Yufukuai** [comment]
[Save Folder (Ask for permission)](https://drive.google.com/file/d/1UXijjTu5n8ps8brCMm433sSDnUJCJ4PB/view?usp=sharing) This was the save folder before NomNom fixed itself

**Comment by cengelha** [comment]
Please check and let me know if the issue persists in the latest version (3.7.0.20).
