### ISSUE TITLE
[Feature Request] Adjust Player Height Scale

### ISSUE THREAD

**Issue by FiftyTifty** [cengelha/NomNom#72]
### Description
With GoatFungus' save editor, you were able to view the JSON data for the save, and were able to modify the following field: **PlayerStateData** -> **CharacterCustomisationData** -> **[0]** ->**"Scale"**

By editing that, you can directly modify your character's height. Having access to this would be fabulous, particularly for WALL-E type characters.

**Comment by cengelha** [comment]
You can already do it the same way in NomNom (for now just use Ctrl + F to search) but a feature to customise some things directly via UI are already planned.

**Comment by FiftyTifty** [comment]
Ooh, I didn't know we could do that. I missed the advanced functions setting, which allows us to edit the JSON. Thanks for the heads up.
