### ISSUE TITLE
[Feature Request] Support for No Mans Sky Sentinel Update 3.8

### ISSUE THREAD

**Issue by louanfontenele** [cengelha/NomNom#75]
Please, can you update the Save Editor for 3.8 (Sentinel Update)?

**Comment by stoneylsd** [comment]
That would be amazing if you do 😊

**Comment by cengelha** [comment]
Yes, as soon as MBINCompiler is fully updated to it :) (currently still some necessary parts missing)

**Comment by stoneylsd** [comment]
> Yes, as soon as MBINCompiler is fully updated to it :) (currently still some necessary parts missing)

Awesome 👏, can't wait .
