### ISSUE TITLE
I can't use save editor after Outlaws update

### ISSUE THREAD

**Issue by FoxChanHelpful** [cengelha/NomNom#83]
### Description
After the outlaws update, I tried using the save editor but after saving the save and launching no mans sky, the save hasn't been updated yet it shows in NomNom the modifications I made edit: When i click on the save it auto loads manual save instead.

1. Go to NomNom
2. Click on Save File
3. Edit
4. Save

![image](https://user-images.githubusercontent.com/72468609/165000202-fde641d8-fda7-467a-875c-d7d15ed180a2.png)
![image](https://user-images.githubusercontent.com/72468609/165000218-d7a3b3ed-f646-44f1-be42-9c3b5eceb5d1.png)

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version: Outlaws 3.88
 - Platform: Microsoft Store

**Comment by Nan0bit** [comment]
This is still happening for me on the latest version of both the Game and NomNom
