### ISSUE TITLE
[Feature Request] update?

### ISSUE THREAD

**Issue by SuperMcFamous** [cengelha/NomNom#91]
Is there anytime that the editor will be updated by any chance? I've had no issues and I'm thankful for the editor because it definitely works great for the fact that I have the game on PC via Xbox Game Pass. Thanks in advance!

**Comment by cengelha** [comment]
Hi, I check regularly but the dependency of my update script wasn't fully updated yet and therefore there is no update yet. As soon as it works, I'll finish the update :)
