### ISSUE TITLE
[Bug] Crach when open Edit save data menu

### ISSUE THREAD

**Issue by mepy888** [cengelha/NomNom#98]
### Description
Crach when open Edit save data menu back to windwos no prompt or anything

### Files
 save, crash report  and log file in archive.

### Additional Context
Account data and Catalog work 
 - Version: last github + last steam
 - Platform: steam
[report.zip](https://github.com/cengelha/NomNom/files/9844773/report.zip)

**Comment by buanzo** [comment]
+1 - It's been happening since Waypoint.
